// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddConsumptionWindow: typeof import('./components/AddConsumptionWindow.vue')['default']
    Alert: typeof import('./components/Alert.vue')['default']
    Board: typeof import('./components/Board.vue')['default']
    BoardConsumptionDetails: typeof import('./components/BoardConsumptionDetails.vue')['default']
    Canvas: typeof import('./components/Canvas.vue')['default']
    CardPopupContent: typeof import('./components/CardPopupContent.vue')['default']
    CardPopupHeader: typeof import('./components/CardPopupHeader.vue')['default']
    EnergyIcon: typeof import('./components/EnergyIcon.vue')['default']
    EnergyMenu: typeof import('./components/EnergyMenu.vue')['default']
    EquipementList: typeof import('./components/EquipementList.vue')['default']
    Equipments: typeof import('./components/Equipments.vue')['default']
    GameBoardSnackBar: typeof import('./components/GameBoardSnackBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeCreateGame: typeof import('./components/HomeCreateGame.vue')['default']
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    ProductionList: typeof import('./components/ProductionList.vue')['default']
    ProductionResume: typeof import('./components/ProductionResume.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioList: typeof import('./components/ScenarioList.vue')['default']
    ScenarioResume: typeof import('./components/ScenarioResume.vue')['default']
    SetupValidationSection: typeof import('./components/SetupValidationSection.vue')['default']
    ValidationSetup: typeof import('./components/ValidationSetup.vue')['default']
  }
}
