// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddConsumptionWindow: typeof import('./components/AddConsumptionWindow.vue')['default']
    Alert: typeof import('./components/Alert.vue')['default']
    Board: typeof import('./components/Board.vue')['default']
    BoardConsumptionDetails: typeof import('./components/BoardConsumptionDetails.vue')['default']
    Canvas: typeof import('./components/Canvas.vue')['default']
    CardPopupContent: typeof import('./components/CardPopupContent.vue')['default']
    CardPopupHeader: typeof import('./components/CardPopupHeader.vue')['default']
    EquipementList: typeof import('./components/EquipementList.vue')['default']
    Equipments: typeof import('./components/Equipments.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
