/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./components/BaseAlert.vue')['default']
    BaseCanvas: typeof import('./components/BaseCanvas.vue')['default']
    BaseMenuIcon: typeof import('./components/BaseMenuIcon.vue')['default']
    BaseToggleSwitch: typeof import('./components/BaseToggleSwitch.vue')['default']
    Board: typeof import('./components/Board.vue')['default']
    BoardConsumptionAddWindow: typeof import('./components/BoardConsumptionAddWindow.vue')['default']
    BoardConsumptionDetails: typeof import('./components/BoardConsumptionDetails.vue')['default']
    BoardConsumptionDetailsWindow: typeof import('./components/BoardConsumptionDetailsWindow.vue')['default']
    BoardIconsBar: typeof import('./components/BoardIconsBar.vue')['default']
    CardPopup: typeof import('./components/CardPopup.vue')['default']
    CardPopupAmountModifier: typeof import('./components/CardPopupAmountModifier.vue')['default']
    CardPopupContent: typeof import('./components/CardPopupContent.vue')['default']
    CardPopupHeader: typeof import('./components/CardPopupHeader.vue')['default']
    CardPopupModificationButtons: typeof import('./components/CardPopupModificationButtons.vue')['default']
    CardPopupSaveButtons: typeof import('./components/CardPopupSaveButtons.vue')['default']
    CardPopupTimeModifier: typeof import('./components/CardPopupTimeModifier.vue')['default']
    EnergyMenu: typeof import('./components/EnergyMenu.vue')['default']
    EnergyMenuAddEnergyWindow: typeof import('./components/EnergyMenuAddEnergyWindow.vue')['default']
    EnergyMenuIcon: typeof import('./components/EnergyMenuIcon.vue')['default']
    EnergyMenuUseEnergyWindow: typeof import('./components/EnergyMenuUseEnergyWindow.vue')['default']
    EquipmentList: typeof import('./components/EquipmentList.vue')['default']
    EquipmentListEquipment: typeof import('./components/EquipmentListEquipment.vue')['default']
    HomeCreateGame: typeof import('./components/HomeCreateGame.vue')['default']
    HomeJoinGame: typeof import('./components/HomeJoinGame.vue')['default']
    MarketMenu: typeof import('./components/MarketMenu.vue')['default']
    MarketMenuIcon: typeof import('./components/MarketMenuIcon.vue')['default']
    MoneyMenuIcon: typeof import('./components/MoneyMenuIcon.vue')['default']
    MultiplayerMenuIcon: typeof import('./components/MultiplayerMenuIcon.vue')['default']
    ResultsMenuConfirmation: typeof import('./components/ResultsMenuConfirmation.vue')['default']
    ResultsMenuIcon: typeof import('./components/ResultsMenuIcon.vue')['default']
    ResultsSituationDisplay: typeof import('./components/ResultsSituationDisplay.vue')['default']
    ResultsSituationDisplayIndicators: typeof import('./components/ResultsSituationDisplayIndicators.vue')['default']
    ResultsSituationDisplayIndicatorsIndicator: typeof import('./components/ResultsSituationDisplayIndicatorsIndicator.vue')['default']
    ResultsSituationDisplayIndicatorsRate: typeof import('./components/ResultsSituationDisplayIndicatorsRate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMenu: typeof import('./components/SettingsMenu.vue')['default']
    SettingsMenuIcon: typeof import('./components/SettingsMenuIcon.vue')['default']
    SetupProductionList: typeof import('./components/SetupProductionList.vue')['default']
    SetupProductionResume: typeof import('./components/SetupProductionResume.vue')['default']
    SetupScenarioList: typeof import('./components/SetupScenarioList.vue')['default']
    SetupScenarioResume: typeof import('./components/SetupScenarioResume.vue')['default']
    SetupValidationSection: typeof import('./components/SetupValidationSection.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
    TheGameInfoWindow: typeof import('./components/TheGameInfoWindow.vue')['default']
    TheLanguageSelector: typeof import('./components/TheLanguageSelector.vue')['default']
  }
}
